// <auto-generated />
namespace BogMenu.Migrations.Menu
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update17 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update17));
        
        string IMigrationMetadata.Id
        {
            get { return "201810160235379_update 17"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
