// <auto-generated />
namespace BogMenu.Migrations.Menu
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update15 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update15));
        
        string IMigrationMetadata.Id
        {
            get { return "201810152327569_update 15"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
